// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=./mock/interface.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	messaging "github.com/zercle/zercle-go-template/internal/features/chat/messaging"
	gomock "go.uber.org/mock/gomock"
)

// MockPubSubServiceInterface is a mock of PubSubServiceInterface interface.
type MockPubSubServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPubSubServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockPubSubServiceInterfaceMockRecorder is the mock recorder for MockPubSubServiceInterface.
type MockPubSubServiceInterfaceMockRecorder struct {
	mock *MockPubSubServiceInterface
}

// NewMockPubSubServiceInterface creates a new mock instance.
func NewMockPubSubServiceInterface(ctrl *gomock.Controller) *MockPubSubServiceInterface {
	mock := &MockPubSubServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPubSubServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPubSubServiceInterface) EXPECT() *MockPubSubServiceInterfaceMockRecorder {
	return m.recorder
}

// PublishMessage mocks base method.
func (m *MockPubSubServiceInterface) PublishMessage(ctx context.Context, roomID string, event messaging.MessageEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishMessage", ctx, roomID, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishMessage indicates an expected call of PublishMessage.
func (mr *MockPubSubServiceInterfaceMockRecorder) PublishMessage(ctx, roomID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMessage", reflect.TypeOf((*MockPubSubServiceInterface)(nil).PublishMessage), ctx, roomID, event)
}

// PublishPresence mocks base method.
func (m *MockPubSubServiceInterface) PublishPresence(ctx context.Context, roomID string, event messaging.PresenceEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPresence", ctx, roomID, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPresence indicates an expected call of PublishPresence.
func (mr *MockPubSubServiceInterfaceMockRecorder) PublishPresence(ctx, roomID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPresence", reflect.TypeOf((*MockPubSubServiceInterface)(nil).PublishPresence), ctx, roomID, event)
}

// PublishTyping mocks base method.
func (m *MockPubSubServiceInterface) PublishTyping(ctx context.Context, roomID, userID string, event messaging.TypingEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishTyping", ctx, roomID, userID, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishTyping indicates an expected call of PublishTyping.
func (mr *MockPubSubServiceInterfaceMockRecorder) PublishTyping(ctx, roomID, userID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishTyping", reflect.TypeOf((*MockPubSubServiceInterface)(nil).PublishTyping), ctx, roomID, userID, event)
}
