// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	domain "github.com/zercle/zercle-go-template/internal/features/reporting/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetOverview mocks base method.
func (m *MockRepository) GetOverview(ctx context.Context) (domain.Overview, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOverview", ctx)
	ret0, _ := ret[0].(domain.Overview)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOverview indicates an expected call of GetOverview.
func (mr *MockRepositoryMockRecorder) GetOverview(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOverview", reflect.TypeOf((*MockRepository)(nil).GetOverview), ctx)
}

// GetTopMachines mocks base method.
func (m *MockRepository) GetTopMachines(ctx context.Context, limit int32) ([]domain.MachineSales, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopMachines", ctx, limit)
	ret0, _ := ret[0].([]domain.MachineSales)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopMachines indicates an expected call of GetTopMachines.
func (mr *MockRepositoryMockRecorder) GetTopMachines(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopMachines", reflect.TypeOf((*MockRepository)(nil).GetTopMachines), ctx, limit)
}
