// Code generated by MockGen. DO NOT EDIT.
// Source: jwt_usecase.go
//
// Generated by this command:
//
//	mockgen -source=jwt_usecase.go -destination=./mocks/jwt_usecase_mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	domain "zercle-go-template/internal/feature/auth/domain"

	gomock "go.uber.org/mock/gomock"
)

// MockJWTUsecase is a mock of JWTUsecase interface.
type MockJWTUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockJWTUsecaseMockRecorder
	isgomock struct{}
}

// MockJWTUsecaseMockRecorder is the mock recorder for MockJWTUsecase.
type MockJWTUsecaseMockRecorder struct {
	mock *MockJWTUsecase
}

// NewMockJWTUsecase creates a new mock instance.
func NewMockJWTUsecase(ctrl *gomock.Controller) *MockJWTUsecase {
	mock := &MockJWTUsecase{ctrl: ctrl}
	mock.recorder = &MockJWTUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTUsecase) EXPECT() *MockJWTUsecaseMockRecorder {
	return m.recorder
}

// GenerateAccessToken mocks base method.
func (m *MockJWTUsecase) GenerateAccessToken(claims *domain.JWTClaims) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAccessToken", claims)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAccessToken indicates an expected call of GenerateAccessToken.
func (mr *MockJWTUsecaseMockRecorder) GenerateAccessToken(claims any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAccessToken", reflect.TypeOf((*MockJWTUsecase)(nil).GenerateAccessToken), claims)
}

// GenerateTokenPair mocks base method.
func (m *MockJWTUsecase) GenerateTokenPair(user domain.TokenUser) (*domain.TokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateTokenPair", user)
	ret0, _ := ret[0].(*domain.TokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateTokenPair indicates an expected call of GenerateTokenPair.
func (mr *MockJWTUsecaseMockRecorder) GenerateTokenPair(user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateTokenPair", reflect.TypeOf((*MockJWTUsecase)(nil).GenerateTokenPair), user)
}

// ValidateToken mocks base method.
func (m *MockJWTUsecase) ValidateToken(tokenString string) (*domain.JWTClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateToken", tokenString)
	ret0, _ := ret[0].(*domain.JWTClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateToken indicates an expected call of ValidateToken.
func (mr *MockJWTUsecaseMockRecorder) ValidateToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateToken", reflect.TypeOf((*MockJWTUsecase)(nil).ValidateToken), tokenString)
}
