// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mock/interface.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	echo "github.com/labstack/echo/v4"
	model "github.com/zercle/zercle-go-template/domain/payment/model"
	request "github.com/zercle/zercle-go-template/domain/payment/request"
	response "github.com/zercle/zercle-go-template/domain/payment/response"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Confirm mocks base method.
func (m *MockRepository) Confirm(ctx context.Context, id uuid.UUID) (*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Confirm", ctx, id)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Confirm indicates an expected call of Confirm.
func (mr *MockRepositoryMockRecorder) Confirm(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Confirm", reflect.TypeOf((*MockRepository)(nil).Confirm), ctx, id)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, payment *model.Payment) (*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, payment)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, payment any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, payment)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// GetByBookingID mocks base method.
func (m *MockRepository) GetByBookingID(ctx context.Context, bookingID uuid.UUID) (*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBookingID", ctx, bookingID)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBookingID indicates an expected call of GetByBookingID.
func (mr *MockRepositoryMockRecorder) GetByBookingID(ctx, bookingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBookingID", reflect.TypeOf((*MockRepository)(nil).GetByBookingID), ctx, bookingID)
}

// GetByID mocks base method.
func (m *MockRepository) GetByID(ctx context.Context, id uuid.UUID) (*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRepository)(nil).GetByID), ctx, id)
}

// GetByTransactionID mocks base method.
func (m *MockRepository) GetByTransactionID(ctx context.Context, transactionID string) (*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTransactionID", ctx, transactionID)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTransactionID indicates an expected call of GetByTransactionID.
func (mr *MockRepositoryMockRecorder) GetByTransactionID(ctx, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTransactionID", reflect.TypeOf((*MockRepository)(nil).GetByTransactionID), ctx, transactionID)
}

// ListByBooking mocks base method.
func (m *MockRepository) ListByBooking(ctx context.Context, bookingID uuid.UUID) ([]*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByBooking", ctx, bookingID)
	ret0, _ := ret[0].([]*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByBooking indicates an expected call of ListByBooking.
func (mr *MockRepositoryMockRecorder) ListByBooking(ctx, bookingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByBooking", reflect.TypeOf((*MockRepository)(nil).ListByBooking), ctx, bookingID)
}

// ListByStatus mocks base method.
func (m *MockRepository) ListByStatus(ctx context.Context, status string, limit, offset int) ([]*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStatus", ctx, status, limit, offset)
	ret0, _ := ret[0].([]*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByStatus indicates an expected call of ListByStatus.
func (mr *MockRepositoryMockRecorder) ListByStatus(ctx, status, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStatus", reflect.TypeOf((*MockRepository)(nil).ListByStatus), ctx, status, limit, offset)
}

// Refund mocks base method.
func (m *MockRepository) Refund(ctx context.Context, id uuid.UUID) (*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refund", ctx, id)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Refund indicates an expected call of Refund.
func (mr *MockRepositoryMockRecorder) Refund(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refund", reflect.TypeOf((*MockRepository)(nil).Refund), ctx, id)
}

// UpdateStatus mocks base method.
func (m *MockRepository) UpdateStatus(ctx context.Context, id uuid.UUID, status model.PaymentStatus, transactionID string) (*model.Payment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status, transactionID)
	ret0, _ := ret[0].(*model.Payment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockRepositoryMockRecorder) UpdateStatus(ctx, id, status, transactionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockRepository)(nil).UpdateStatus), ctx, id, status, transactionID)
}

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// ConfirmPayment mocks base method.
func (m *MockUsecase) ConfirmPayment(ctx context.Context, id uuid.UUID) (*response.PaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmPayment", ctx, id)
	ret0, _ := ret[0].(*response.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmPayment indicates an expected call of ConfirmPayment.
func (mr *MockUsecaseMockRecorder) ConfirmPayment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmPayment", reflect.TypeOf((*MockUsecase)(nil).ConfirmPayment), ctx, id)
}

// CreatePayment mocks base method.
func (m *MockUsecase) CreatePayment(ctx context.Context, req request.CreatePayment) (*response.PaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", ctx, req)
	ret0, _ := ret[0].(*response.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockUsecaseMockRecorder) CreatePayment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockUsecase)(nil).CreatePayment), ctx, req)
}

// GetPayment mocks base method.
func (m *MockUsecase) GetPayment(ctx context.Context, id uuid.UUID) (*response.PaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayment", ctx, id)
	ret0, _ := ret[0].(*response.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPayment indicates an expected call of GetPayment.
func (mr *MockUsecaseMockRecorder) GetPayment(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayment", reflect.TypeOf((*MockUsecase)(nil).GetPayment), ctx, id)
}

// GetPaymentByBooking mocks base method.
func (m *MockUsecase) GetPaymentByBooking(ctx context.Context, bookingID uuid.UUID) (*response.PaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByBooking", ctx, bookingID)
	ret0, _ := ret[0].(*response.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPaymentByBooking indicates an expected call of GetPaymentByBooking.
func (mr *MockUsecaseMockRecorder) GetPaymentByBooking(ctx, bookingID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByBooking", reflect.TypeOf((*MockUsecase)(nil).GetPaymentByBooking), ctx, bookingID)
}

// ListPayments mocks base method.
func (m *MockUsecase) ListPayments(ctx context.Context, req request.ListPayments) (*response.ListPaymentsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPayments", ctx, req)
	ret0, _ := ret[0].(*response.ListPaymentsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPayments indicates an expected call of ListPayments.
func (mr *MockUsecaseMockRecorder) ListPayments(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPayments", reflect.TypeOf((*MockUsecase)(nil).ListPayments), ctx, req)
}

// RefundPayment mocks base method.
func (m *MockUsecase) RefundPayment(ctx context.Context, id uuid.UUID, req request.RefundPayment) (*response.PaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefundPayment", ctx, id, req)
	ret0, _ := ret[0].(*response.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefundPayment indicates an expected call of RefundPayment.
func (mr *MockUsecaseMockRecorder) RefundPayment(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefundPayment", reflect.TypeOf((*MockUsecase)(nil).RefundPayment), ctx, id, req)
}

// UpdatePaymentStatus mocks base method.
func (m *MockUsecase) UpdatePaymentStatus(ctx context.Context, id uuid.UUID, req request.UpdatePaymentStatus) (*response.PaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePaymentStatus", ctx, id, req)
	ret0, _ := ret[0].(*response.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdatePaymentStatus indicates an expected call of UpdatePaymentStatus.
func (mr *MockUsecaseMockRecorder) UpdatePaymentStatus(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePaymentStatus", reflect.TypeOf((*MockUsecase)(nil).UpdatePaymentStatus), ctx, id, req)
}

// MockHandler is a mock of Handler interface.
type MockHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHandlerMockRecorder
	isgomock struct{}
}

// MockHandlerMockRecorder is the mock recorder for MockHandler.
type MockHandlerMockRecorder struct {
	mock *MockHandler
}

// NewMockHandler creates a new mock instance.
func NewMockHandler(ctrl *gomock.Controller) *MockHandler {
	mock := &MockHandler{ctrl: ctrl}
	mock.recorder = &MockHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHandler) EXPECT() *MockHandlerMockRecorder {
	return m.recorder
}

// ConfirmPayment mocks base method.
func (m *MockHandler) ConfirmPayment(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmPayment", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// ConfirmPayment indicates an expected call of ConfirmPayment.
func (mr *MockHandlerMockRecorder) ConfirmPayment(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmPayment", reflect.TypeOf((*MockHandler)(nil).ConfirmPayment), c)
}

// CreatePayment mocks base method.
func (m *MockHandler) CreatePayment(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePayment", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePayment indicates an expected call of CreatePayment.
func (mr *MockHandlerMockRecorder) CreatePayment(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePayment", reflect.TypeOf((*MockHandler)(nil).CreatePayment), c)
}

// GetPayment mocks base method.
func (m *MockHandler) GetPayment(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPayment", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetPayment indicates an expected call of GetPayment.
func (mr *MockHandlerMockRecorder) GetPayment(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPayment", reflect.TypeOf((*MockHandler)(nil).GetPayment), c)
}

// GetPaymentByBooking mocks base method.
func (m *MockHandler) GetPaymentByBooking(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPaymentByBooking", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetPaymentByBooking indicates an expected call of GetPaymentByBooking.
func (mr *MockHandlerMockRecorder) GetPaymentByBooking(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPaymentByBooking", reflect.TypeOf((*MockHandler)(nil).GetPaymentByBooking), c)
}

// ListPayments mocks base method.
func (m *MockHandler) ListPayments(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPayments", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// ListPayments indicates an expected call of ListPayments.
func (mr *MockHandlerMockRecorder) ListPayments(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPayments", reflect.TypeOf((*MockHandler)(nil).ListPayments), c)
}

// RefundPayment mocks base method.
func (m *MockHandler) RefundPayment(c echo.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefundPayment", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefundPayment indicates an expected call of RefundPayment.
func (mr *MockHandlerMockRecorder) RefundPayment(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefundPayment", reflect.TypeOf((*MockHandler)(nil).RefundPayment), c)
}
