// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"

	"github.com/google/uuid"
)

type Post struct {
	ID        uuid.UUID    `json:"id"`
	Title     string       `json:"title"`
	Content   string       `json:"content"`
	AuthorID  uuid.UUID    `json:"authorId"`
	CreatedAt sql.NullTime `json:"createdAt"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
}

type User struct {
	ID           uuid.UUID      `json:"id"`
	Email        string         `json:"email"`
	PasswordHash string         `json:"passwordHash"`
	FirstName    sql.NullString `json:"firstName"`
	LastName     sql.NullString `json:"lastName"`
	IsActive     sql.NullBool   `json:"isActive"`
	CreatedAt    sql.NullTime   `json:"createdAt"`
	UpdatedAt    sql.NullTime   `json:"updatedAt"`
	DeletedAt    sql.NullTime   `json:"deletedAt"`
}
