// Code generated by MockGen. DO NOT EDIT.
// Source: pubsub.go
//
// Generated by this command:
//
//	mockgen -source=pubsub.go -destination=../mocks/pubsub.mock.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/zercle/zercle-go-template/internal/feature/chat/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockPubSubService is a mock of PubSubService interface.
type MockPubSubService struct {
	ctrl     *gomock.Controller
	recorder *MockPubSubServiceMockRecorder
	isgomock struct{}
}

// MockPubSubServiceMockRecorder is the mock recorder for MockPubSubService.
type MockPubSubServiceMockRecorder struct {
	mock *MockPubSubService
}

// NewMockPubSubService creates a new mock instance.
func NewMockPubSubService(ctrl *gomock.Controller) *MockPubSubService {
	mock := &MockPubSubService{ctrl: ctrl}
	mock.recorder = &MockPubSubServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPubSubService) EXPECT() *MockPubSubServiceMockRecorder {
	return m.recorder
}

// PublishMessage mocks base method.
func (m *MockPubSubService) PublishMessage(ctx context.Context, roomID string, event domain.MessageEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishMessage", ctx, roomID, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishMessage indicates an expected call of PublishMessage.
func (mr *MockPubSubServiceMockRecorder) PublishMessage(ctx, roomID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishMessage", reflect.TypeOf((*MockPubSubService)(nil).PublishMessage), ctx, roomID, event)
}

// PublishPresence mocks base method.
func (m *MockPubSubService) PublishPresence(ctx context.Context, roomID string, event domain.PresenceEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPresence", ctx, roomID, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishPresence indicates an expected call of PublishPresence.
func (mr *MockPubSubServiceMockRecorder) PublishPresence(ctx, roomID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPresence", reflect.TypeOf((*MockPubSubService)(nil).PublishPresence), ctx, roomID, event)
}

// PublishTyping mocks base method.
func (m *MockPubSubService) PublishTyping(ctx context.Context, roomID, userID string, event domain.TypingEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishTyping", ctx, roomID, userID, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishTyping indicates an expected call of PublishTyping.
func (mr *MockPubSubServiceMockRecorder) PublishTyping(ctx, roomID, userID, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishTyping", reflect.TypeOf((*MockPubSubService)(nil).PublishTyping), ctx, roomID, userID, event)
}
