// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Message struct {
	ID          uuid.UUID
	RoomID      pgtype.UUID
	SenderID    pgtype.UUID
	Content     string
	MessageType pgtype.Text
	ReplyTo     pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	RevokedAt pgtype.Timestamptz
}

type Room struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
	Type        string
	OwnerID     pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	DeletedAt   pgtype.Timestamptz
}

type RoomMember struct {
	RoomID   uuid.UUID
	UserID   uuid.UUID
	Role     pgtype.Text
	JoinedAt pgtype.Timestamptz
}

type User struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	DisplayName  pgtype.Text
	AvatarUrl    pgtype.Text
	Status       pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
	DeletedAt    pgtype.Timestamptz
}
