// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=./mock/interface.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	domain "github.com/zercle/zercle-go-template/internal/features/chat/domain"
	service "github.com/zercle/zercle-go-template/internal/features/chat/service"
	gomock "go.uber.org/mock/gomock"
)

// MockChatServiceInterface is a mock of ChatServiceInterface interface.
type MockChatServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockChatServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockChatServiceInterfaceMockRecorder is the mock recorder for MockChatServiceInterface.
type MockChatServiceInterfaceMockRecorder struct {
	mock *MockChatServiceInterface
}

// NewMockChatServiceInterface creates a new mock instance.
func NewMockChatServiceInterface(ctrl *gomock.Controller) *MockChatServiceInterface {
	mock := &MockChatServiceInterface{ctrl: ctrl}
	mock.recorder = &MockChatServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChatServiceInterface) EXPECT() *MockChatServiceInterfaceMockRecorder {
	return m.recorder
}

// CreateRoom mocks base method.
func (m *MockChatServiceInterface) CreateRoom(ctx context.Context, input service.CreateRoomInput) (*domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRoom", ctx, input)
	ret0, _ := ret[0].(*domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRoom indicates an expected call of CreateRoom.
func (mr *MockChatServiceInterfaceMockRecorder) CreateRoom(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRoom", reflect.TypeOf((*MockChatServiceInterface)(nil).CreateRoom), ctx, input)
}

// DeleteRoom mocks base method.
func (m *MockChatServiceInterface) DeleteRoom(ctx context.Context, roomID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRoom", ctx, roomID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRoom indicates an expected call of DeleteRoom.
func (mr *MockChatServiceInterfaceMockRecorder) DeleteRoom(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRoom", reflect.TypeOf((*MockChatServiceInterface)(nil).DeleteRoom), ctx, roomID)
}

// GetMessageHistory mocks base method.
func (m *MockChatServiceInterface) GetMessageHistory(ctx context.Context, roomID uuid.UUID, limit, offset int, before *uuid.UUID) ([]*domain.Message, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageHistory", ctx, roomID, limit, offset, before)
	ret0, _ := ret[0].([]*domain.Message)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetMessageHistory indicates an expected call of GetMessageHistory.
func (mr *MockChatServiceInterfaceMockRecorder) GetMessageHistory(ctx, roomID, limit, offset, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageHistory", reflect.TypeOf((*MockChatServiceInterface)(nil).GetMessageHistory), ctx, roomID, limit, offset, before)
}

// GetRoom mocks base method.
func (m *MockChatServiceInterface) GetRoom(ctx context.Context, roomID uuid.UUID) (*domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoom", ctx, roomID)
	ret0, _ := ret[0].(*domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoom indicates an expected call of GetRoom.
func (mr *MockChatServiceInterfaceMockRecorder) GetRoom(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoom", reflect.TypeOf((*MockChatServiceInterface)(nil).GetRoom), ctx, roomID)
}

// GetRoomMembers mocks base method.
func (m *MockChatServiceInterface) GetRoomMembers(ctx context.Context, roomID uuid.UUID) ([]*domain.RoomMember, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRoomMembers", ctx, roomID)
	ret0, _ := ret[0].([]*domain.RoomMember)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRoomMembers indicates an expected call of GetRoomMembers.
func (mr *MockChatServiceInterfaceMockRecorder) GetRoomMembers(ctx, roomID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRoomMembers", reflect.TypeOf((*MockChatServiceInterface)(nil).GetRoomMembers), ctx, roomID)
}

// JoinRoom mocks base method.
func (m *MockChatServiceInterface) JoinRoom(ctx context.Context, roomID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "JoinRoom", ctx, roomID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// JoinRoom indicates an expected call of JoinRoom.
func (mr *MockChatServiceInterfaceMockRecorder) JoinRoom(ctx, roomID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "JoinRoom", reflect.TypeOf((*MockChatServiceInterface)(nil).JoinRoom), ctx, roomID, userID)
}

// LeaveRoom mocks base method.
func (m *MockChatServiceInterface) LeaveRoom(ctx context.Context, roomID, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LeaveRoom", ctx, roomID, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LeaveRoom indicates an expected call of LeaveRoom.
func (mr *MockChatServiceInterfaceMockRecorder) LeaveRoom(ctx, roomID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LeaveRoom", reflect.TypeOf((*MockChatServiceInterface)(nil).LeaveRoom), ctx, roomID, userID)
}

// ListRooms mocks base method.
func (m *MockChatServiceInterface) ListRooms(ctx context.Context, userID uuid.UUID, limit, offset int) ([]*domain.Room, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRooms", ctx, userID, limit, offset)
	ret0, _ := ret[0].([]*domain.Room)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListRooms indicates an expected call of ListRooms.
func (mr *MockChatServiceInterfaceMockRecorder) ListRooms(ctx, userID, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRooms", reflect.TypeOf((*MockChatServiceInterface)(nil).ListRooms), ctx, userID, limit, offset)
}

// SendMessage mocks base method.
func (m *MockChatServiceInterface) SendMessage(ctx context.Context, input service.SendMessageInput) (*domain.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", ctx, input)
	ret0, _ := ret[0].(*domain.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockChatServiceInterfaceMockRecorder) SendMessage(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockChatServiceInterface)(nil).SendMessage), ctx, input)
}

// UpdateRoom mocks base method.
func (m *MockChatServiceInterface) UpdateRoom(ctx context.Context, roomID uuid.UUID, name, description string) (*domain.Room, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRoom", ctx, roomID, name, description)
	ret0, _ := ret[0].(*domain.Room)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRoom indicates an expected call of UpdateRoom.
func (mr *MockChatServiceInterfaceMockRecorder) UpdateRoom(ctx, roomID, name, description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRoom", reflect.TypeOf((*MockChatServiceInterface)(nil).UpdateRoom), ctx, roomID, name, description)
}
