apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zercle-go-template
  namespace: zercle-go-template
  annotations:
    nginx.ingress.kubernetes.io/rate-limit: "100"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - api.example.com
      secretName: tls-secret
  rules:
    - host: api.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zercle-go-template
                port:
                  number: 8080