apiVersion: v1
kind: Secret
metadata:
  name: zercle-go-template-secrets
  namespace: zercle-go-template
type: Opaque
stringData:
  DB_PASSWORD: "CHANGE_ME"
  DB_USER: "CHANGE_ME"
  CACHE_PASSWORD: "CHANGE_ME"
  AUTH_ACCESS_TOKEN_SECRET: "CHANGE_ME"
  AUTH_REFRESH_TOKEN_SECRET: "CHANGE_ME"