// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

<<<<<<<< HEAD:internal/infrastructure/db/postgres/db.go
package postgres
========
package sqlcauth
>>>>>>>> 955a9e9 (feat(test): add comprehensive test coverage and performance optimizations):internal/infrastructure/database/sqlc/auth/db.go

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
)

type DBTX interface {
	Exec(context.Context, string, ...interface{}) (pgconn.CommandTag, error)
	Query(context.Context, string, ...interface{}) (pgx.Rows, error)
	QueryRow(context.Context, string, ...interface{}) pgx.Row
}

func New(db DBTX) *Queries {
	return &Queries{db: db}
}

type Queries struct {
	db DBTX
}

func (q *Queries) WithTx(tx pgx.Tx) *Queries {
	return &Queries{
		db: tx,
	}
}
