// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Check if a user with the given email exists
	CheckUserExists(ctx context.Context, email string) (bool, error)
	// Get the total number of users
	CountUsers(ctx context.Context) (int64, error)
	// Create a new user and return the created record
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Delete a user by their ID
	DeleteUser(ctx context.Context, id uuid.UUID) error
	// Get a user by their email address
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Get a user by their ID
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	// Get all users with pagination support
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	// Update an existing user and return the updated record
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
