// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: bookings.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelBooking = `-- name: CancelBooking :one
UPDATE bookings
SET status = 'cancelled', cancelled_at = $2, updated_at = $3
WHERE id = $1
RETURNING id, user_id, service_id, start_time, end_time, status, total_price, notes, cancelled_at, created_at, updated_at
`

type CancelBookingParams struct {
	ID          pgtype.UUID        `json:"id"`
	CancelledAt pgtype.Timestamptz `json:"cancelled_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CancelBooking(ctx context.Context, arg CancelBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, cancelBooking, arg.ID, arg.CancelledAt, arg.UpdatedAt)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.TotalPrice,
		&i.Notes,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const checkBookingConflict = `-- name: CheckBookingConflict :many
SELECT id, user_id, service_id, start_time, end_time, status, total_price, notes, cancelled_at, created_at, updated_at FROM bookings
WHERE service_id = $1
  AND status NOT IN ('cancelled', 'completed')
  AND (
    (start_time < $2 AND end_time > $2) OR
    (start_time < $3 AND end_time > $3) OR
    (start_time >= $2 AND end_time <= $3)
  )
`

type CheckBookingConflictParams struct {
	ServiceID   pgtype.UUID        `json:"service_id"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	StartTime_2 pgtype.Timestamptz `json:"start_time_2"`
}

func (q *Queries) CheckBookingConflict(ctx context.Context, arg CheckBookingConflictParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, checkBookingConflict, arg.ServiceID, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.TotalPrice,
			&i.Notes,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (id, user_id, service_id, start_time, end_time, status, total_price, notes, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, user_id, service_id, start_time, end_time, status, total_price, notes, cancelled_at, created_at, updated_at
`

type CreateBookingParams struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	ServiceID  pgtype.UUID        `json:"service_id"`
	StartTime  pgtype.Timestamptz `json:"start_time"`
	EndTime    pgtype.Timestamptz `json:"end_time"`
	Status     string             `json:"status"`
	TotalPrice pgtype.Numeric     `json:"total_price"`
	Notes      pgtype.Text        `json:"notes"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.ID,
		arg.UserID,
		arg.ServiceID,
		arg.StartTime,
		arg.EndTime,
		arg.Status,
		arg.TotalPrice,
		arg.Notes,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.TotalPrice,
		&i.Notes,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBooking = `-- name: DeleteBooking :exec
DELETE FROM bookings
WHERE id = $1
`

func (q *Queries) DeleteBooking(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBooking, id)
	return err
}

const getActiveBookingsCount = `-- name: GetActiveBookingsCount :one
SELECT COUNT(*) FROM bookings
WHERE service_id = $1
  AND status NOT IN ('cancelled', 'completed')
  AND (
    (start_time < $2 AND end_time > $2) OR
    (start_time < $3 AND end_time > $3) OR
    (start_time >= $2 AND end_time <= $3)
  )
`

type GetActiveBookingsCountParams struct {
	ServiceID   pgtype.UUID        `json:"service_id"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	StartTime_2 pgtype.Timestamptz `json:"start_time_2"`
}

func (q *Queries) GetActiveBookingsCount(ctx context.Context, arg GetActiveBookingsCountParams) (int64, error) {
	row := q.db.QueryRow(ctx, getActiveBookingsCount, arg.ServiceID, arg.StartTime, arg.StartTime_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBooking = `-- name: GetBooking :one
SELECT id, user_id, service_id, start_time, end_time, status, total_price, notes, cancelled_at, created_at, updated_at FROM bookings
WHERE id = $1
`

func (q *Queries) GetBooking(ctx context.Context, id pgtype.UUID) (Booking, error) {
	row := q.db.QueryRow(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.TotalPrice,
		&i.Notes,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBookingStats = `-- name: GetBookingStats :one
SELECT 
    COUNT(*) as total_bookings,
    COUNT(*) FILTER (WHERE status = 'pending') as pending_count,
    COUNT(*) FILTER (WHERE status = 'confirmed') as confirmed_count,
    COUNT(*) FILTER (WHERE status = 'completed') as completed_count,
    COUNT(*) FILTER (WHERE status = 'cancelled') as cancelled_count,
    COALESCE(SUM(total_price), 0) as total_revenue
FROM bookings
WHERE created_at >= $1 AND created_at <= $2
`

type GetBookingStatsParams struct {
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	CreatedAt_2 pgtype.Timestamptz `json:"created_at_2"`
}

type GetBookingStatsRow struct {
	TotalBookings  int64       `json:"total_bookings"`
	PendingCount   int64       `json:"pending_count"`
	ConfirmedCount int64       `json:"confirmed_count"`
	CompletedCount int64       `json:"completed_count"`
	CancelledCount int64       `json:"cancelled_count"`
	TotalRevenue   interface{} `json:"total_revenue"`
}

func (q *Queries) GetBookingStats(ctx context.Context, arg GetBookingStatsParams) (GetBookingStatsRow, error) {
	row := q.db.QueryRow(ctx, getBookingStats, arg.CreatedAt, arg.CreatedAt_2)
	var i GetBookingStatsRow
	err := row.Scan(
		&i.TotalBookings,
		&i.PendingCount,
		&i.ConfirmedCount,
		&i.CompletedCount,
		&i.CancelledCount,
		&i.TotalRevenue,
	)
	return i, err
}

const listBookingsByDateRange = `-- name: ListBookingsByDateRange :many
SELECT id, user_id, service_id, start_time, end_time, status, total_price, notes, cancelled_at, created_at, updated_at FROM bookings
WHERE start_time >= $1 AND start_time <= $2
ORDER BY start_time ASC
LIMIT $3 OFFSET $4
`

type ListBookingsByDateRangeParams struct {
	StartTime   pgtype.Timestamptz `json:"start_time"`
	StartTime_2 pgtype.Timestamptz `json:"start_time_2"`
	Limit       int32              `json:"limit"`
	Offset      int32              `json:"offset"`
}

func (q *Queries) ListBookingsByDateRange(ctx context.Context, arg ListBookingsByDateRangeParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByDateRange,
		arg.StartTime,
		arg.StartTime_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.TotalPrice,
			&i.Notes,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByService = `-- name: ListBookingsByService :many
SELECT id, user_id, service_id, start_time, end_time, status, total_price, notes, cancelled_at, created_at, updated_at FROM bookings
WHERE service_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBookingsByServiceParams struct {
	ServiceID pgtype.UUID `json:"service_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListBookingsByService(ctx context.Context, arg ListBookingsByServiceParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByService, arg.ServiceID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.TotalPrice,
			&i.Notes,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByServiceAndDateRange = `-- name: ListBookingsByServiceAndDateRange :many
SELECT id, user_id, service_id, start_time, end_time, status, total_price, notes, cancelled_at, created_at, updated_at FROM bookings
WHERE service_id = $1 AND start_time >= $2 AND start_time <= $3
ORDER BY start_time ASC
`

type ListBookingsByServiceAndDateRangeParams struct {
	ServiceID   pgtype.UUID        `json:"service_id"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	StartTime_2 pgtype.Timestamptz `json:"start_time_2"`
}

func (q *Queries) ListBookingsByServiceAndDateRange(ctx context.Context, arg ListBookingsByServiceAndDateRangeParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByServiceAndDateRange, arg.ServiceID, arg.StartTime, arg.StartTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.TotalPrice,
			&i.Notes,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByStatus = `-- name: ListBookingsByStatus :many
SELECT id, user_id, service_id, start_time, end_time, status, total_price, notes, cancelled_at, created_at, updated_at FROM bookings
WHERE status = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBookingsByStatusParams struct {
	Status string `json:"status"`
	Limit  int32  `json:"limit"`
	Offset int32  `json:"offset"`
}

func (q *Queries) ListBookingsByStatus(ctx context.Context, arg ListBookingsByStatusParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByStatus, arg.Status, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.TotalPrice,
			&i.Notes,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsByUser = `-- name: ListBookingsByUser :many
SELECT id, user_id, service_id, start_time, end_time, status, total_price, notes, cancelled_at, created_at, updated_at FROM bookings
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListBookingsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListBookingsByUser(ctx context.Context, arg ListBookingsByUserParams) ([]Booking, error) {
	rows, err := q.db.Query(ctx, listBookingsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Booking
	for rows.Next() {
		var i Booking
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ServiceID,
			&i.StartTime,
			&i.EndTime,
			&i.Status,
			&i.TotalPrice,
			&i.Notes,
			&i.CancelledAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :one
UPDATE bookings
SET status = $2, updated_at = $3
WHERE id = $1
RETURNING id, user_id, service_id, start_time, end_time, status, total_price, notes, cancelled_at, created_at, updated_at
`

type UpdateBookingStatusParams struct {
	ID        pgtype.UUID        `json:"id"`
	Status    string             `json:"status"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error) {
	row := q.db.QueryRow(ctx, updateBookingStatus, arg.ID, arg.Status, arg.UpdatedAt)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ServiceID,
		&i.StartTime,
		&i.EndTime,
		&i.Status,
		&i.TotalPrice,
		&i.Notes,
		&i.CancelledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
