// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AvailabilitySlot struct {
	ID          pgtype.UUID        `json:"id"`
	ServiceID   pgtype.UUID        `json:"service_id"`
	DayOfWeek   int32              `json:"day_of_week"`
	StartTime   pgtype.Time        `json:"start_time"`
	EndTime     pgtype.Time        `json:"end_time"`
	MaxBookings int32              `json:"max_bookings"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Booking struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	ServiceID   pgtype.UUID        `json:"service_id"`
	StartTime   pgtype.Timestamptz `json:"start_time"`
	EndTime     pgtype.Timestamptz `json:"end_time"`
	Status      string             `json:"status"`
	TotalPrice  pgtype.Numeric     `json:"total_price"`
	Notes       pgtype.Text        `json:"notes"`
	CancelledAt pgtype.Timestamptz `json:"cancelled_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type BookingsUser struct {
	BookingID pgtype.UUID `json:"booking_id"`
	UserID    pgtype.UUID `json:"user_id"`
	IsPrimary bool        `json:"is_primary"`
}

type Payment struct {
	ID            pgtype.UUID        `json:"id"`
	BookingID     pgtype.UUID        `json:"booking_id"`
	Amount        pgtype.Numeric     `json:"amount"`
	Status        string             `json:"status"`
	PaymentMethod pgtype.Text        `json:"payment_method"`
	TransactionID pgtype.Text        `json:"transaction_id"`
	PaidAt        pgtype.Timestamptz `json:"paid_at"`
	RefundedAt    pgtype.Timestamptz `json:"refunded_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Service struct {
	ID              pgtype.UUID        `json:"id"`
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	DurationMinutes int32              `json:"duration_minutes"`
	Price           pgtype.Numeric     `json:"price"`
	MaxCapacity     int32              `json:"max_capacity"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     string             `json:"full_name"`
	Phone        pgtype.Text        `json:"phone"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
