// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelBooking(ctx context.Context, arg CancelBookingParams) (Booking, error)
	CheckBookingConflict(ctx context.Context, arg CheckBookingConflictParams) ([]Booking, error)
	ConfirmPayment(ctx context.Context, arg ConfirmPaymentParams) (Payment, error)
	CreateAvailabilitySlot(ctx context.Context, arg CreateAvailabilitySlotParams) (AvailabilitySlot, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateBookingUser(ctx context.Context, arg CreateBookingUserParams) error
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateService(ctx context.Context, arg CreateServiceParams) (Service, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAvailabilitySlot(ctx context.Context, id pgtype.UUID) error
	DeleteBooking(ctx context.Context, id pgtype.UUID) error
	DeleteBookingUser(ctx context.Context, arg DeleteBookingUserParams) error
	DeleteBookingUsers(ctx context.Context, bookingID pgtype.UUID) error
	DeletePayment(ctx context.Context, id pgtype.UUID) error
	DeleteService(ctx context.Context, id pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetActiveBookingsCount(ctx context.Context, arg GetActiveBookingsCountParams) (int64, error)
	GetAvailabilitySlot(ctx context.Context, id pgtype.UUID) (AvailabilitySlot, error)
	GetAvailabilitySlotForDayAndTime(ctx context.Context, arg GetAvailabilitySlotForDayAndTimeParams) (AvailabilitySlot, error)
	GetBooking(ctx context.Context, id pgtype.UUID) (Booking, error)
	GetBookingStats(ctx context.Context, arg GetBookingStatsParams) (GetBookingStatsRow, error)
	GetBookingUsers(ctx context.Context, bookingID pgtype.UUID) ([]User, error)
	GetPayment(ctx context.Context, id pgtype.UUID) (Payment, error)
	GetPaymentByBooking(ctx context.Context, bookingID pgtype.UUID) (Payment, error)
	GetPaymentByTransactionId(ctx context.Context, transactionID pgtype.Text) (Payment, error)
	GetPaymentStats(ctx context.Context, arg GetPaymentStatsParams) (GetPaymentStatsRow, error)
	GetPrimaryBookingUser(ctx context.Context, bookingID pgtype.UUID) (User, error)
	GetService(ctx context.Context, id pgtype.UUID) (Service, error)
	GetServicesByIds(ctx context.Context, dollar_1 []pgtype.UUID) ([]Service, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListAllAvailabilitySlots(ctx context.Context) ([]AvailabilitySlot, error)
	ListAvailabilitySlotsByService(ctx context.Context, arg ListAvailabilitySlotsByServiceParams) ([]AvailabilitySlot, error)
	ListBookingsByDateRange(ctx context.Context, arg ListBookingsByDateRangeParams) ([]Booking, error)
	ListBookingsByService(ctx context.Context, arg ListBookingsByServiceParams) ([]Booking, error)
	ListBookingsByServiceAndDateRange(ctx context.Context, arg ListBookingsByServiceAndDateRangeParams) ([]Booking, error)
	ListBookingsByStatus(ctx context.Context, arg ListBookingsByStatusParams) ([]Booking, error)
	ListBookingsByUser(ctx context.Context, arg ListBookingsByUserParams) ([]Booking, error)
	ListPaymentsByBooking(ctx context.Context, bookingID pgtype.UUID) ([]Payment, error)
	ListPaymentsByStatus(ctx context.Context, arg ListPaymentsByStatusParams) ([]Payment, error)
	ListServices(ctx context.Context, arg ListServicesParams) ([]Service, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RefundPayment(ctx context.Context, arg RefundPaymentParams) (Payment, error)
	SearchServicesByName(ctx context.Context, arg SearchServicesByNameParams) ([]Service, error)
	SearchUsersByEmail(ctx context.Context, arg SearchUsersByEmailParams) ([]User, error)
	SetPrimaryBookingUser(ctx context.Context, arg SetPrimaryBookingUserParams) error
	UpdateAvailabilitySlot(ctx context.Context, arg UpdateAvailabilitySlotParams) (AvailabilitySlot, error)
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) (Booking, error)
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
