// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: services.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createService = `-- name: CreateService :one
INSERT INTO services (name, description, duration_minutes, price, max_capacity, is_active, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, name, description, duration_minutes, price, max_capacity, is_active, created_at, updated_at
`

type CreateServiceParams struct {
	Name            string             `json:"name"`
	Description     pgtype.Text        `json:"description"`
	DurationMinutes int32              `json:"duration_minutes"`
	Price           pgtype.Numeric     `json:"price"`
	MaxCapacity     int32              `json:"max_capacity"`
	IsActive        bool               `json:"is_active"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
		arg.Price,
		arg.MaxCapacity,
		arg.IsActive,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.Price,
		&i.MaxCapacity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services
WHERE id = $1
`

func (q *Queries) DeleteService(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getService = `-- name: GetService :one
SELECT id, name, description, duration_minutes, price, max_capacity, is_active, created_at, updated_at FROM services
WHERE id = $1
`

func (q *Queries) GetService(ctx context.Context, id pgtype.UUID) (Service, error) {
	row := q.db.QueryRow(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.Price,
		&i.MaxCapacity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getServicesByIds = `-- name: GetServicesByIds :many
SELECT id, name, description, duration_minutes, price, max_capacity, is_active, created_at, updated_at FROM services
WHERE id = ANY($1::uuid[])
ORDER BY created_at DESC
`

func (q *Queries) GetServicesByIds(ctx context.Context, dollar_1 []pgtype.UUID) ([]Service, error) {
	rows, err := q.db.Query(ctx, getServicesByIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.Price,
			&i.MaxCapacity,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listServices = `-- name: ListServices :many
SELECT id, name, description, duration_minutes, price, max_capacity, is_active, created_at, updated_at FROM services
WHERE is_active = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListServicesParams struct {
	IsActive bool  `json:"is_active"`
	Limit    int32 `json:"limit"`
	Offset   int32 `json:"offset"`
}

func (q *Queries) ListServices(ctx context.Context, arg ListServicesParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, listServices, arg.IsActive, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.Price,
			&i.MaxCapacity,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchServicesByName = `-- name: SearchServicesByName :many
SELECT id, name, description, duration_minutes, price, max_capacity, is_active, created_at, updated_at FROM services
WHERE name ILIKE $1 AND is_active = $2
ORDER BY created_at DESC
LIMIT $3
`

type SearchServicesByNameParams struct {
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
	Limit    int32  `json:"limit"`
}

func (q *Queries) SearchServicesByName(ctx context.Context, arg SearchServicesByNameParams) ([]Service, error) {
	rows, err := q.db.Query(ctx, searchServicesByName, arg.Name, arg.IsActive, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Service
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.DurationMinutes,
			&i.Price,
			&i.MaxCapacity,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE services
SET name = COALESCE($3, name),
    description = COALESCE($4, description),
    duration_minutes = COALESCE($5, duration_minutes),
    price = COALESCE($6, price),
    max_capacity = COALESCE($7, max_capacity),
    is_active = COALESCE($8, is_active),
    updated_at = $2
WHERE id = $1
RETURNING id, name, description, duration_minutes, price, max_capacity, is_active, created_at, updated_at
`

type UpdateServiceParams struct {
	ID              pgtype.UUID        `json:"id"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Name            pgtype.Text        `json:"name"`
	Description     pgtype.Text        `json:"description"`
	DurationMinutes pgtype.Int4        `json:"duration_minutes"`
	Price           pgtype.Numeric     `json:"price"`
	MaxCapacity     pgtype.Int4        `json:"max_capacity"`
	IsActive        pgtype.Bool        `json:"is_active"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (Service, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.UpdatedAt,
		arg.Name,
		arg.Description,
		arg.DurationMinutes,
		arg.Price,
		arg.MaxCapacity,
		arg.IsActive,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.DurationMinutes,
		&i.Price,
		&i.MaxCapacity,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
