// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlctask

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countTasks = `-- name: CountTasks :one
SELECT COUNT(*) FROM tasks
WHERE ($1::uuid IS NULL OR user_id = $1)
  AND ($2::varchar IS NULL OR status = $2)
  AND ($3::varchar IS NULL OR priority = $3)
`

type CountTasksParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 string      `json:"column_2"`
	Column3 string      `json:"column_3"`
}

func (q *Queries) CountTasks(ctx context.Context, arg *CountTasksParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTasks, arg.Column1, arg.Column2, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
    id,
    title,
    description,
    status,
    priority,
    user_id,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, title, description, status, priority, user_id, created_at, updated_at
`

type CreateTaskParams struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	Priority    string             `json:"priority"`
	UserID      uuid.UUID          `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg *CreateTaskParams) (*Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const existsTaskByID = `-- name: ExistsTaskByID :one
SELECT EXISTS(SELECT 1 FROM tasks WHERE id = $1)
`

func (q *Queries) ExistsTaskByID(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsTaskByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, title, description, status, priority, user_id, created_at, updated_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id uuid.UUID) (*Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listTasks = `-- name: ListTasks :many
SELECT id, title, description, status, priority, user_id, created_at, updated_at FROM tasks
WHERE ($1::uuid IS NULL OR user_id = $1)
  AND ($2::varchar IS NULL OR status = $2)
  AND ($3::varchar IS NULL OR priority = $3)
ORDER BY created_at DESC
LIMIT $4 OFFSET $5
`

type ListTasksParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 string      `json:"column_2"`
	Column3 string      `json:"column_3"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListTasks(ctx context.Context, arg *ListTasksParams) ([]*Task, error) {
	rows, err := q.db.Query(ctx, listTasks,
		arg.Column1,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*Task{}
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.UserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET
    title = $2,
    description = $3,
    status = $4,
    priority = $5,
    updated_at = $6
WHERE id = $1
RETURNING id, title, description, status, priority, user_id, created_at, updated_at
`

type UpdateTaskParams struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Status      string             `json:"status"`
	Priority    string             `json:"priority"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg *UpdateTaskParams) (*Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.UpdatedAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
