// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlccredential

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCredential = `-- name: CreateCredential :one
INSERT INTO user_credentials (
    id,
    user_id,
    password_hash,
    created_at,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, password_hash, created_at, updated_at
`

type CreateCredentialParams struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCredential(ctx context.Context, arg *CreateCredentialParams) (*UserCredential, error) {
	row := q.db.QueryRow(ctx, createCredential,
		arg.ID,
		arg.UserID,
		arg.PasswordHash,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteCredentialByUserID = `-- name: DeleteCredentialByUserID :exec
DELETE FROM user_credentials WHERE user_id = $1
`

func (q *Queries) DeleteCredentialByUserID(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCredentialByUserID, userID)
	return err
}

const existsCredentialByUserID = `-- name: ExistsCredentialByUserID :one
SELECT EXISTS(SELECT 1 FROM user_credentials WHERE user_id = $1)
`

func (q *Queries) ExistsCredentialByUserID(ctx context.Context, userID uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, existsCredentialByUserID, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCredentialByUserID = `-- name: GetCredentialByUserID :one
SELECT id, user_id, password_hash, created_at, updated_at FROM user_credentials WHERE user_id = $1
`

func (q *Queries) GetCredentialByUserID(ctx context.Context, userID uuid.UUID) (*UserCredential, error) {
	row := q.db.QueryRow(ctx, getCredentialByUserID, userID)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateCredentialPassword = `-- name: UpdateCredentialPassword :one
UPDATE user_credentials SET
    password_hash = $2,
    updated_at = $3
WHERE user_id = $1
RETURNING id, user_id, password_hash, created_at, updated_at
`

type UpdateCredentialPasswordParams struct {
	UserID       uuid.UUID          `json:"user_id"`
	PasswordHash string             `json:"password_hash"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCredentialPassword(ctx context.Context, arg *UpdateCredentialPasswordParams) (*UserCredential, error) {
	row := q.db.QueryRow(ctx, updateCredentialPassword, arg.UserID, arg.PasswordHash, arg.UpdatedAt)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
