// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addRoomMember = `-- name: AddRoomMember :exec
INSERT INTO room_members (room_id, user_id, role, joined_at)
VALUES ($1, $2, $3, $4)
`

type AddRoomMemberParams struct {
	RoomID   uuid.UUID
	UserID   uuid.UUID
	Role     pgtype.Text
	JoinedAt pgtype.Timestamptz
}

func (q *Queries) AddRoomMember(ctx context.Context, arg AddRoomMemberParams) error {
	_, err := q.db.Exec(ctx, addRoomMember,
		arg.RoomID,
		arg.UserID,
		arg.Role,
		arg.JoinedAt,
	)
	return err
}

const createMessage = `-- name: CreateMessage :exec
INSERT INTO messages (id, room_id, sender_id, content, message_type, reply_to, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateMessageParams struct {
	ID          uuid.UUID
	RoomID      pgtype.UUID
	SenderID    pgtype.UUID
	Content     string
	MessageType pgtype.Text
	ReplyTo     pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) error {
	_, err := q.db.Exec(ctx, createMessage,
		arg.ID,
		arg.RoomID,
		arg.SenderID,
		arg.Content,
		arg.MessageType,
		arg.ReplyTo,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (id, user_id, token, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type CreateRefreshTokenParams struct {
	ID        uuid.UUID
	UserID    pgtype.UUID
	Token     string
	ExpiresAt pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const createRoom = `-- name: CreateRoom :exec
INSERT INTO rooms (id, name, description, type, owner_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateRoomParams struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
	Type        string
	OwnerID     pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) error {
	_, err := q.db.Exec(ctx, createRoom,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.OwnerID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, email, password_hash, display_name, avatar_url, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateUserParams struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	DisplayName  pgtype.Text
	AvatarUrl    pgtype.Text
	Status       pgtype.Text
	CreatedAt    pgtype.Timestamptz
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteMessage = `-- name: DeleteMessage :exec
UPDATE messages SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteMessage(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessage, id)
	return err
}

const deleteRefreshTokenByUserID = `-- name: DeleteRefreshTokenByUserID :exec
DELETE FROM refresh_tokens WHERE user_id = $1
`

func (q *Queries) DeleteRefreshTokenByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRefreshTokenByUserID, userID)
	return err
}

const deleteRoom = `-- name: DeleteRoom :exec
UPDATE rooms SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteRoom(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRoom, id)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
UPDATE users SET deleted_at = NOW() WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getMessageByID = `-- name: GetMessageByID :one
SELECT id, room_id, sender_id, content, message_type, reply_to, created_at, updated_at, deleted_at
FROM messages
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetMessageByID(ctx context.Context, id uuid.UUID) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByID, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.SenderID,
		&i.Content,
		&i.MessageType,
		&i.ReplyTo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMessageHistory = `-- name: GetMessageHistory :many
SELECT id, room_id, sender_id, content, message_type, reply_to, created_at, updated_at, deleted_at
FROM messages
WHERE room_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetMessageHistoryParams struct {
	RoomID pgtype.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) GetMessageHistory(ctx context.Context, arg GetMessageHistoryParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getMessageHistory, arg.RoomID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.SenderID,
			&i.Content,
			&i.MessageType,
			&i.ReplyTo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token, expires_at, created_at, revoked_at
FROM refresh_tokens
WHERE token = $1 AND revoked_at IS NULL
`

func (q *Queries) GetRefreshToken(ctx context.Context, token string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, token)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, description, type, owner_id, created_at, updated_at, deleted_at
FROM rooms
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRoomByID(ctx context.Context, id uuid.UUID) (Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Type,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoomMember = `-- name: GetRoomMember :one
SELECT room_id, user_id, role, joined_at
FROM room_members
WHERE room_id = $1 AND user_id = $2
`

type GetRoomMemberParams struct {
	RoomID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetRoomMember(ctx context.Context, arg GetRoomMemberParams) (RoomMember, error) {
	row := q.db.QueryRow(ctx, getRoomMember, arg.RoomID, arg.UserID)
	var i RoomMember
	err := row.Scan(
		&i.RoomID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getRoomMembers = `-- name: GetRoomMembers :many
SELECT rm.room_id, rm.user_id, rm.role, rm.joined_at, u.username, u.email, u.display_name, u.avatar_url, u.status
FROM room_members rm
JOIN users u ON rm.user_id = u.id
WHERE rm.room_id = $1 AND u.deleted_at IS NULL
`

type GetRoomMembersRow struct {
	RoomID      uuid.UUID
	UserID      uuid.UUID
	Role        pgtype.Text
	JoinedAt    pgtype.Timestamptz
	Username    string
	Email       string
	DisplayName pgtype.Text
	AvatarUrl   pgtype.Text
	Status      pgtype.Text
}

func (q *Queries) GetRoomMembers(ctx context.Context, roomID uuid.UUID) ([]GetRoomMembersRow, error) {
	rows, err := q.db.Query(ctx, getRoomMembers, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRoomMembersRow
	for rows.Next() {
		var i GetRoomMembersRow
		if err := rows.Scan(
			&i.RoomID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Username,
			&i.Email,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, display_name, avatar_url, status, created_at, updated_at, deleted_at
FROM users
WHERE email = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, display_name, avatar_url, status, created_at, updated_at, deleted_at
FROM users
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password_hash, display_name, avatar_url, status, created_at, updated_at, deleted_at
FROM users
WHERE username = $1 AND deleted_at IS NULL
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listRooms = `-- name: ListRooms :many
SELECT id, name, description, type, owner_id, created_at, updated_at, deleted_at
FROM rooms
WHERE deleted_at IS NULL
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListRoomsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListRooms(ctx context.Context, arg ListRoomsParams) ([]Room, error) {
	rows, err := q.db.Query(ctx, listRooms, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Room
	for rows.Next() {
		var i Room
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Type,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRoomMember = `-- name: RemoveRoomMember :exec
DELETE FROM room_members WHERE room_id = $1 AND user_id = $2
`

type RemoveRoomMemberParams struct {
	RoomID uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) RemoveRoomMember(ctx context.Context, arg RemoveRoomMemberParams) error {
	_, err := q.db.Exec(ctx, removeRoomMember, arg.RoomID, arg.UserID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = NOW() WHERE token = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, token)
	return err
}

const updateMessage = `-- name: UpdateMessage :exec
UPDATE messages
SET content = $2, updated_at = $3
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateMessageParams struct {
	ID        uuid.UUID
	Content   string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpdateMessage(ctx context.Context, arg UpdateMessageParams) error {
	_, err := q.db.Exec(ctx, updateMessage, arg.ID, arg.Content, arg.UpdatedAt)
	return err
}

const updateRoom = `-- name: UpdateRoom :exec
UPDATE rooms
SET name = $2, description = $3, type = $4, updated_at = $5
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateRoomParams struct {
	ID          uuid.UUID
	Name        string
	Description pgtype.Text
	Type        string
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) error {
	_, err := q.db.Exec(ctx, updateRoom,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Type,
		arg.UpdatedAt,
	)
	return err
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET username = $2, email = $3, password_hash = $4, display_name = $5, avatar_url = $6, status = $7, updated_at = $8
WHERE id = $1 AND deleted_at IS NULL
`

type UpdateUserParams struct {
	ID           uuid.UUID
	Username     string
	Email        string
	PasswordHash string
	DisplayName  pgtype.Text
	AvatarUrl    pgtype.Text
	Status       pgtype.Text
	UpdatedAt    pgtype.Timestamptz
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}
