// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	uuid "uuid"

	domain "github.com/zercle/zercle-go-template/internal/features/sales/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CommitPurchase mocks base method.
func (m *MockRepository) CommitPurchase(ctx context.Context, machineID, productID uuid.UUID, record *domain.PurchaseRecord, bankAfter domain.CoinBank) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitPurchase", ctx, machineID, productID, record, bankAfter)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitPurchase indicates an expected call of CommitPurchase.
func (mr *MockRepositoryMockRecorder) CommitPurchase(ctx, machineID, productID, record, bankAfter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitPurchase", reflect.TypeOf((*MockRepository)(nil).CommitPurchase), ctx, machineID, productID, record, bankAfter)
}

// GetMachineBank mocks base method.
func (m *MockRepository) GetMachineBank(ctx context.Context, machineID uuid.UUID) (domain.CoinBank, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMachineBank", ctx, machineID)
	ret0, _ := ret[0].(domain.CoinBank)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMachineBank indicates an expected call of GetMachineBank.
func (mr *MockRepositoryMockRecorder) GetMachineBank(ctx, machineID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMachineBank", reflect.TypeOf((*MockRepository)(nil).GetMachineBank), ctx, machineID)
}

// GetProduct mocks base method.
func (m *MockRepository) GetProduct(ctx context.Context, productID uuid.UUID) (domain.SaleProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", ctx, productID)
	ret0, _ := ret[0].(domain.SaleProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockRepositoryMockRecorder) GetProduct(ctx, productID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockRepository)(nil).GetProduct), ctx, productID)
}
